version: 2.1

orbs:
  node: circleci/node@4.5.1

jobs:
  test:  
    docker:
      - image: 'cimg/node:14.17.3-browsers'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run server (background)
          command: npm run serve
          background: true
      - run:
          name: Run tests
          command: npm test
  deploy:
    # Ref: https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install gh-pages
          command: npm install --silent gh-pages
      - run:
          name: Setup Git configuration
          command: |
            git config user.email "kelvintaywl@gmail.com"
            git config user.name "CI Build"
      - add_ssh_keys:
          fingerprints:
            - "0d:ce:d5:61:3f:0a:48:52:cb:22:95:72:dc:d2:94:40"
      - run:
          name: Publish to gh-pages branch
          command: npx gh-pages --dotfiles --message "[skip ci] Publish" --dist app

workflows:
  standard: 
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
